# Site settings
course_name: Secure Internet of Things
course_description: "
The goal of the course is to learn necessary concepte to design secure IoT systems. The
course covers basic techniques for threat modeling and security analysis of practical IoT systems.
The course provides a complete overview of different aspects of security (primarily software security) and
standard techniques used to solve various software security problems. We discuss
generic techniques and try to apply them to IoT systems.

For every concept, we will start with basics and specialize them to IoT systems."

evaluation: "
We will use the following distribution for grading:
<ul>
  <li>Four assignments (7% each, Total: 28%).</li>
  <li>Three Homeworks (30%).</li>
  <li>Midterm (20%).</li>
  <li>Final (20%).</li>
  <li>Class Participation (2%).</li>
</ul>"


course_prereqs: "This is a hands-on course and I expect students to be confortable with programming in Python and have basic understanding of software engineering.
<ul>
    <li>ECE 30861.</li>
    <li>ECE 36200.</li>
    <li>ECE 40400 (concurrent).</li>
    <li>Knowledge about basic software security concepts such as buffer overflows, return-oriented programming, etc.</li>
</ul>"

learning_objectives: "This course is aimed at introducing students to designing of Secure IoT systems.
After finishing the course, the students should:
<ul>
    <li>Describe security challenges concerning communication, protecting on-device data, tampering, and attestation in real-world IoT systems.</li>
    <li>Can identify and describe the security threats prevented by using edge computing in IoT systems.</li>
    <li>Apply security design principles, specifically certificate-based authentication and role-based access control, to enable authenticated access to IoT devices.</li>
    <li>Describe and identify security standards and ethics (ISO/IEC, NIST, Cybersecurity Improvement Act) related to the design of IoT systems.</li>
    <li>Given a description and requirements of a system, students can create it with a given set of IoT devices (2-3) and sensors (1-2) using a computing platform (e.g., Amazon AWS, Azure).</li>
    <li>Given specific requirements, students are able to develop secure (with respect to secure data transmission, local data processing, and integration with cloud services) IoT applications that can span a single device or multiple devices (2-3), depending on the requirements.</li>
</ul>
"

course_policies: "This course will be run under the \"reasonable adults\" policy wherein it is assumed that all
students are reasonable adults that want to benefit the most of the course by attending the course regularly,
completing the homework assignments and projects on time, asking questions during the course and if they run
into problems, and checking back with the instructor and the TA (if there exists one) regularly to ensure good progress. <br/>

A more verbose version of the policy is available on <a href=\"https://spaf.cerias.purdue.edu/cpolicy.html\">Spaf's</a> page.
This course follows the policies listed on that page. If you have any question about the course policy,
don't hesitate to ask the instructor or the TA. <br/>

As a short summary: (i) you are expected to attend all classes (modulo good reasons),
(ii) you are supposed to hand in all work before the deadlines (there's a 10% point reduction per day for late hand-ins),
(iii) if you need special treatment or have special circumstances, talk to the instructor or TA. - Copied from Prof.Payers course."

course_semester: "Fall 2026"

nondiscrimination_statement: "Purdue University is committed to maintaining a community which recognizes and
values the inherent worth and dignity of every person; fosters tolerance, sensitivity, understanding, and
mutual respect among its members; and encourages each individual to strive to reach his or her own potential.
In pursuit of its goal of academic excellence, the University seeks to develop and nurture diversity.
The University believes that diversity among its many members strengthens the institution, stimulates creativity,
promotes the exchange of ideas, and enriches campus life. <a href=\"https://www.purdue.edu/purdue/ea_eou_statement.php\">Link to Purdue’s nondiscrimination policy statement</a>."

student_disability: "Purdue University strives to make learning experiences as accessible as possible.
If you anticipate or experience physical or academic barriers based on disability, you are welcome to let me know so that we can discuss options.
You are also encouraged to contact the Disability Resource Center at: drc@purdue.edu or by phone: 765-494-1247"

emergency_preparation: "In the event of a major campus emergency, course requirements, deadlines and grading
percentages are subject to changes that may be necessitated by a revised semester calendar or other circumstances
beyond the instructor’s control. Relevant changes to this course will be posted onto the course website or can be
obtained by contacting the instructors or TAs via email or phone. You are expected to read your @purdue.edu email on a frequent basis."

mental_health: "
It is important to make sure that you maintain your mental health.
<ul>
<li>If you find yourself beginning to feel some stress, anxiety and/or feeling slightly overwhelmed, try WellTrack.
Sign in and find information and tools at your fingertips, available to you at any time. </li>
<li> If you need support and information about options and resources, please see the Office of the Dean of Students for drop-in hours (M-F, 8 am- 5 pm). </li>
<li> If you’re struggling and need mental health services: Purdue University is committed to advancing the mental health
 and well-being of its students. If you or someone you know is feeling overwhelmed, depressed, and/or in need of mental health support,
 services are available.
 For help, such individuals should contact Counseling and Psychological Services (CAPS) at 765-494-6995 during and
 after hours, on weekends and holidays, or by going to the CAPS office of the second floor of the Purdue University
 Student Health Center (PUSH) during business hours.</li>
 <li>TaskHuman offers private, real-time, on-demand, 1-on-1 video calls with wellness coaches covering over 800+ topics
 such as anxiety, mindfulness, reducing stress, clean eating, time management, in-home workouts, relationship tensions,
 financial issues, spiritual guidance and many more. You can access these wellness coaches from around the world 24/7.
 The College of Engineering has an exclusive agreement with TaskHuman which gives you FREE and UNLIMITED access to
 these resources. Over 3,200 calls have been made by College of Engineering students, staff, and faculty so far with an
  average satisfaction rating of 4.89/5.
  Learn more here: https://engineering.purdue.edu/ECE/TaskHuman.</li>
 </ul>"


baseurl: "/siot" # the subpath of your site, e.g. /blog/
url: "http://purs3lab.github.io/" # the base hostname & protocol for your site

schoolname: "Purdue University"
schoolurl: "https://engineering.purdue.edu/ECE"
twitter_username: machiry_msidc

address: |
    Elmore Family School of Electrical and Computer Engineering
    Purdue University
    West Lafayette, IN, USA

# Set your Google Analytics tracking ID (set up yours at http://www.google.com/analytics/)
google_analytics: UA-93239312-1

### Do not change the followings unless you know what you are doing ###

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']
exclude: ['develop']

dateformat: "%m/%d/%Y"

future: true
collections:
    events:
        output: true
    lectures:
        output: true
    lecschedule:
        output: true
    assignments:
        output: true
    announcements:
        output: false


defaults:
  - scope:
      path: ""
      type: "assignments"
    values:
      layout: "assignment"
